//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMAdmin.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oportia.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Leads.
        /// </summary>
        internal static string lblAddLeads {
            get {
                return ResourceManager.GetString("lblAddLeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note.
        /// </summary>
        internal static string lblAddNote {
            get {
                return ResourceManager.GetString("lblAddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Reminder.
        /// </summary>
        internal static string lblAddReminder {
            get {
                return ResourceManager.GetString("lblAddReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        internal static string lblAgent {
            get {
                return ResourceManager.GetString("lblAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        internal static string lblArchive {
            get {
                return ResourceManager.GetString("lblArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to login.
        /// </summary>
        internal static string lblBackToLogin {
            get {
                return ResourceManager.GetString("lblBackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string lblChangePassword {
            get {
                return ResourceManager.GetString("lblChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string lblChat {
            get {
                return ResourceManager.GetString("lblChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string lblConfirmPassword {
            get {
                return ResourceManager.GetString("lblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string lblDashboard {
            get {
                return ResourceManager.GetString("lblDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponible.
        /// </summary>
        internal static string lblDisponible {
            get {
                return ResourceManager.GetString("lblDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string lblDocuments {
            get {
                return ResourceManager.GetString("lblDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit account.
        /// </summary>
        internal static string lblEditAccount {
            get {
                return ResourceManager.GetString("lblEditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Leads.
        /// </summary>
        internal static string lblEditLeads {
            get {
                return ResourceManager.GetString("lblEditLeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Reminder.
        /// </summary>
        internal static string lblEditReminder {
            get {
                return ResourceManager.GetString("lblEditReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string lblEmailAddress {
            get {
                return ResourceManager.GetString("lblEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        internal static string lblEndTime {
            get {
                return ResourceManager.GetString("lblEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your credentials to log in.
        /// </summary>
        internal static string lblEnterCredentials {
            get {
                return ResourceManager.GetString("lblEnterCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email to reset your password.
        /// </summary>
        internal static string lblEnterYourEmail {
            get {
                return ResourceManager.GetString("lblEnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string lblFilter {
            get {
                return ResourceManager.GetString("lblFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string lblFirstName {
            get {
                return ResourceManager.GetString("lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I forgot my password.
        /// </summary>
        internal static string lblForgotMyPassword {
            get {
                return ResourceManager.GetString("lblForgotMyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string lblForgotPassword {
            get {
                return ResourceManager.GetString("lblForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funeral Step.
        /// </summary>
        internal static string lblFuneralStep {
            get {
                return ResourceManager.GetString("lblFuneralStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string lblHour {
            get {
                return ResourceManager.GetString("lblHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string lblInformation {
            get {
                return ResourceManager.GetString("lblInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string lblLastName {
            get {
                return ResourceManager.GetString("lblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead.
        /// </summary>
        internal static string lblLead {
            get {
                return ResourceManager.GetString("lblLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leads.
        /// </summary>
        internal static string lblLeads {
            get {
                return ResourceManager.GetString("lblLeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead status.
        /// </summary>
        internal static string lblLeadStatus {
            get {
                return ResourceManager.GetString("lblLeadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string lblLocation {
            get {
                return ResourceManager.GetString("lblLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string lblLogout {
            get {
                return ResourceManager.GetString("lblLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Appointment.
        /// </summary>
        internal static string lblNewAppointment {
            get {
                return ResourceManager.GetString("lblNewAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Meeting.
        /// </summary>
        internal static string lblNewMeeting {
            get {
                return ResourceManager.GetString("lblNewMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string lblNewPassword {
            get {
                return ResourceManager.GetString("lblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Reminder.
        /// </summary>
        internal static string lblNewReminder {
            get {
                return ResourceManager.GetString("lblNewReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Control.
        /// </summary>
        internal static string lblNoControl {
            get {
                return ResourceManager.GetString("lblNoControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string lblNotes {
            get {
                return ResourceManager.GetString("lblNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string lblNotification {
            get {
                return ResourceManager.GetString("lblNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string lblNotifications {
            get {
                return ResourceManager.GetString("lblNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        internal static string lblOldPassword {
            get {
                return ResourceManager.GetString("lblOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo &amp; Video.
        /// </summary>
        internal static string lblPhotoAndVideo {
            get {
                return ResourceManager.GetString("lblPhotoAndVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string lblProduct {
            get {
                return ResourceManager.GetString("lblProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string lblProfile {
            get {
                return ResourceManager.GetString("lblProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Response.
        /// </summary>
        internal static string lblQuickResponse {
            get {
                return ResourceManager.GetString("lblQuickResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string lblRating {
            get {
                return ResourceManager.GetString("lblRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        internal static string lblReminder {
            get {
                return ResourceManager.GetString("lblReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        internal static string lblResponsible {
            get {
                return ResourceManager.GetString("lblResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string lblRole {
            get {
                return ResourceManager.GetString("lblRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample@mail.com.
        /// </summary>
        internal static string lblSampleMail {
            get {
                return ResourceManager.GetString("lblSampleMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string lblSchedule {
            get {
                return ResourceManager.GetString("lblSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        internal static string lblSeemore {
            get {
                return ResourceManager.GetString("lblSeemore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string lblSend {
            get {
                return ResourceManager.GetString("lblSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send quick response.
        /// </summary>
        internal static string lblSendQuickResponse {
            get {
                return ResourceManager.GetString("lblSendQuickResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        internal static string lblStartTime {
            get {
                return ResourceManager.GetString("lblStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string lblTelephone {
            get {
                return ResourceManager.GetString("lblTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        internal static string lblTimeline {
            get {
                return ResourceManager.GetString("lblTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unread.
        /// </summary>
        internal static string lblUnread {
            get {
                return ResourceManager.GetString("lblUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string lblVersion {
            get {
                return ResourceManager.GetString("lblVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string lblWelcome {
            get {
                return ResourceManager.GetString("lblWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome,.
        /// </summary>
        internal static string lblWelcomeWith {
            get {
                return ResourceManager.GetString("lblWelcomeWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write note....
        /// </summary>
        internal static string lblWriteNote {
            get {
                return ResourceManager.GetString("lblWriteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your message....
        /// </summary>
        internal static string lblWriteYourMessage {
            get {
                return ResourceManager.GetString("lblWriteYourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Close.
        /// </summary>
        internal static string lblYesClose {
            get {
                return ResourceManager.GetString("lblYesClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Delete.
        /// </summary>
        internal static string lblYesDelete {
            get {
                return ResourceManager.GetString("lblYesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete archive lead.
        /// </summary>
        internal static string msgDoYouWantToDeleteArchive {
            get {
                return ResourceManager.GetString("msgDoYouWantToDeleteArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Capital letters, letters, numbers and symbols.
        /// </summary>
        internal static string msgPasswordFormat {
            get {
                return ResourceManager.GetString("msgPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your inbox. If you don&apos;t receive the email within a few minutes, please check your junk or spam folder.
        /// </summary>
        internal static string msgPleaseCheckYourInbox {
            get {
                return ResourceManager.GetString("msgPleaseCheckYourInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have just sent a password reset link to the email:.
        /// </summary>
        internal static string msgSendPasswordLink {
            get {
                return ResourceManager.GetString("msgSendPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to the email:.
        /// </summary>
        internal static string msgToThelink {
            get {
                return ResourceManager.GetString("msgToThelink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to log out?.
        /// </summary>
        internal static string msgWouldYouLikeToLogout {
            get {
                return ResourceManager.GetString("msgWouldYouLikeToLogout", resourceCulture);
            }
        }
    }
}
